In [16]:
#2.1constant()方法
import tensorflow as tf 

In [17]:
tf.constant(1) #創建一個張量

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [15]:
tf.constant(1.) #創建一個浮點型張量

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [18]:
tf.constant(2, dtype=tf.double) #創建的同時指定數據類型

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [21]:
tf.constant([[1.,2.,3.],[4.,5.,6.]]) #通過傳入一個list參數創建

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [26]:
#2.2convert_to_tensor()方法
import numpy as np

In [31]:
tf.convert_to_tensor(np.ones([2,3])) #轉換為張量

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [29]:
tf.convert_to_tensor([[2.,3.],[3.,4.]])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [3., 4.]], dtype=float32)>

In [32]:
#2.3創建元素為指定值的tensor
#(1)zeros() ones()
a = tf.zeros([2,3,3])
a

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [33]:
b = tf.ones([2,3])
b

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [34]:
#(2)zeros_like ones_like
tf.zeros_like(b) #仿照b的shape創建一個全為0的tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [35]:
tf.ones_like(a) #仿照a的shape創建一個全為1的tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [36]:
#fill() 填入
tf.fill([2,3],5) #創建元素全為5,shape為[2,3]的向量

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[5, 5, 5],
       [5, 5, 5]], dtype=int32)>

In [41]:
#2.4隨機初始化
#(1)tf.random.normal() 從指定正態分布中隨機取值
tf.random.normal([2,3], mean=1, stddev=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.8828365 , -0.42216563,  2.3328931 ],
       [ 0.36725485, -0.54503524,  2.2242446 ]], dtype=float32)>

In [40]:
#truncated_normal() 從指定的截斷正態分布中隨機取值,但取值在兩個標準差範圍內
tf.random.truncated_normal([2, 3], mean=1, stddev=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2.7922049, 1.8258665, 1.6531641],
       [1.7398162, 0.6671749, 1.7433434]], dtype=float32)>