In [5]:
import tensorflow as tf
a=tf.range(1,13)
tf.pad(a, [[5,5]])
a=tf.reshape(a, [2,2,3])
a, tf.pad(a, [[1,1],[2,2],[3,3]]) 


(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>,
 <tf.Tensor: shape=(4, 6, 9), dtype=int32, numpy=
 array([[[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0]],
 
        [[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  1,  2,  3,  0,  0,  0],
         [ 0,  0,  0,  4,  5,  6,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0]],
 
        [[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  7,  8,  9,  0,  0,  0],
         [ 0,  0,  0, 10, 11, 12,  0,  0,  0],
         [ 0,  0,  0,  0,  0, 

In [7]:
a=tf.range(12)
a, tf.tile(a, [2])

(<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
         5,  6,  7,  8,  9, 10, 11], dtype=int32)>)

In [10]:
b=tf.range(5)
b, tf.reshape(a,[3,4])

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=int32)>)

In [11]:
a=tf.range(10)
a, tf.maximum(a, 4), tf.minimum(a,4)

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([4, 4, 4, 4, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 4, 4, 4, 4, 4], dtype=int32)>)